name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@v1.2.0
    with:
      image: ubuntu-22.04
      python-version: "3.10"
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_STUBS }}
