name: publish

on:
  release:
    types:
      - published

jobs:
  tox:
    uses: coatl-dev/workflows/.github/workflows/tox.yml@coatl

  pypi-publish:
    needs: 
      - tox
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@coatl
    with:
      python-version: '3.11'
    secrets:
      password: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_STUBS }}
