name: publish

on:
  release:
    types:
      - published

jobs:
  tox:
    uses: coatl-dev/workflows/.github/workflows/tox.yml@v3

  pypi-publish:
    needs: 
      - tox
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@v3
    secrets:
      password: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_STUBS }}
